Initial refactor release gha

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -34,45 +34,38 @@ jobs:
         with:
           pull_token: ${{ secrets.PULL_TOKEN }}
 
-      - name: Set nightly flag
+      - name: Set test flag
         run: |
-          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "IS_NIGHTLY=true" >> $GITHUB_ENV
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "IS_TEST=true" >> $GITHUB_ENV
           else
-            echo "IS_NIGHTLY=false" >> $GITHUB_ENV
+            echo "IS_TEST=false" >> $GITHUB_ENV
           fi
 
-      # If it's a nightly release, tag with the release time. If the tag is `develop`, we want to use
-      # `latest` as the tag name. Else, use the tag name as is.
+      # If it's a test release, tag with the release time. Else, use the tag name as is.
       - name: Compute release name and tag
         id: release_info
         run: |
-          echo "IS_NIGHTLY=$IS_NIGHTLY"
+          echo "IS_TEST=$IS_TEST"
           echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
 
-          if [[ $IS_NIGHTLY == "true" ]]; then
-            echo "IS_NIGHTLY"
-            echo "tag_name=nightly-${GITHUB_SHA}"
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))"
-            echo "tag_name=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
-          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
-            echo "IS_LATEST"
-            echo "tag_name=latest"
-            echo "release_name=Latest"
-            echo "tag_name=latest" >> $GITHUB_OUTPUT
-            echo "release_name=Latest" >> $GITHUB_OUTPUT
+          if [[ $IS_TEST == "true" ]]; then
+            echo "IS_TEST"
+            echo "tag_name=test-${GITHUB_SHA}"
+            echo "release_name=Test ($(date '+%Y-%m-%d'))"
+            echo "tag_name=test-${GITHUB_SHA}" >> $GITHUB_OUTPUT
+            echo "release_name=Test ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
           else
+            echo "tag_name=${GITHUB_REF_NAME}"
+            echo "release_name=${GITHUB_REF_NAME}"
             echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
             echo "release_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
+          else  
           fi
 
-      # Creates a `nightly-SHA` tag for this specific nightly
-      # This tag is used for this specific nightly version's release
-      # which allows users to roll back. It is also used to build
-      # the changelog.
-      - name: Create build-specific nightly tag
-        if: ${{ env.IS_NIGHTLY == 'true' }}
+      # Creates a `test-SHA` tag for this specific test release
+      - name: Create build-specific test tag
+        if: ${{ env.IS_TEST == 'true' }}
         uses: actions/github-script@v7
         env:
           TAG_NAME: ${{ steps.release_info.outputs.tag_name }}
@@ -86,7 +79,7 @@ jobs:
         uses: mikepenz/release-changelog-builder-action@v4
         with:
           configuration: "./.github/changelog.json"
-          fromTag: ${{ env.IS_NIGHTLY == 'true' && 'nightly' || '' }}
+          fromTag: ${{ env.IS_TEST == 'true' && 'test' || '' }}
           toTag: ${{ steps.release_info.outputs.tag_name }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -183,14 +176,14 @@ jobs:
           key: ${{ matrix.target }}
           cache-on-failure: true
 
-      - name: Install go
-        uses: actions/setup-go@v5
-        with:
-          go-version: "^1.22.1"
+      # - name: Install go
+      #   uses: actions/setup-go@v5
+      #   with:
+      #     go-version: "^1.22.1"
 
-      - name: Check go installation
-        run: |
-          go version
+      # - name: Check go installation
+      #   run: |
+      #     go version
 
       - name: Set up git private repo access
         run: |
@@ -255,17 +248,23 @@ jobs:
           [[ "$target" == *windows* ]] && exe=".exe"
 
           # RUSTFLAGS with correct path and debugging
-          export RUSTFLAGS="-L${IOMP5_DIR} -liomp5"
-          echo "RUSTFLAGS set to: $RUSTFLAGS"
+          # export RUSTFLAGS="-L${IOMP5_DIR} -liomp5"
+          # echo "RUSTFLAGS set to: $RUSTFLAGS"
 
           # Debug: Check Rust and Cargo versions
           echo "🔍 Rust and Cargo versions:"
           rustc --version
           cargo --version
 
-          # Build with debugging
-          echo "🚀 Starting cargo build..."
-          cargo build --release --target "$target" "${flags[@]}"
+          # Build bins with debugging
+          echo "🚀 Starting cargo bins build..."
+          RUSTFLAGS='-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5' cargo build --release --all-features -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
+          # cargo build --release --target "$target" "${flags[@]}"
+
+          # Build libzisk_witness.so with debugging
+          echo "🚀 Starting libzisk_witness.so build..."
+          RUSTFLAGS='-L${IOMP5_DIR} -liomp5' cargo build --release -p zisk-witness --target "$target" "${flags[@]}"
+          # cargo build --release --target "$target" "${flags[@]}"
 
           # Verify built binaries
           bins=(cargo-zisk ziskemu keccakf_fixed_gen riscv2zisk rom-merkle)
@@ -279,18 +278,18 @@ jobs:
             fi
           done
 
-          # libraries=(libzisk_witness.so)
-          # for name in "${libraries[@]}"; do
-          #   bin=./target/$target/release/$name
-          #   echo "🔍 Verifying binary library: $bin"
-          #   file "$bin" || echo "⚠️  file command failed on $bin"
-          #   ldd "$bin" || echo "⚠️  ldd command failed on $bin"
-          # done
+          libraries=(libzisk_witness.so)
+          for name in "${libraries[@]}"; do
+            bin=./target/$target/release/$name
+            echo "🔍 Verifying binary library: $bin"
+            file "$bin" || echo "⚠️  file command failed on $bin"
+            ldd "$bin" || echo "⚠️  ldd command failed on $bin"
+          done
 
           echo "✅ Build process completed."
 
       - name: Set VERSION_NAME
-        run: echo "VERSION_NAME=$([ \"$IS_NIGHTLY\" == 'true' ] && echo 'nightly' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
+        run: echo "VERSION_NAME=$([ \"$IS_TEST\" == 'true' ] && echo 'test' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
 
       - name: Archive binaries
         id: artifacts
@@ -324,45 +323,45 @@ jobs:
         with:
           name: ${{ needs.prepare.outputs.release_name }}
           tag_name: ${{ needs.prepare.outputs.tag_name }}
-          prerelease: ${{ env.IS_NIGHTLY == 'true' || needs.prepare.outputs.tag_name == 'latest' }}
+          draft: ${{ env.IS_TEST == 'true' }}
           body: ${{ needs.prepare.outputs.changelog }}
           files: |
             ${{ steps.artifacts.outputs.file_name }}
 
-      # If this is a nightly release, it also updates the release
-      # tagged `nightly` for compatibility with `ziskup`
-      - name: Update nightly release
-        if: ${{ env.IS_NIGHTLY == 'true' }}
-        uses: softprops/action-gh-release@v1
-        with:
-          name: "Nightly"
-          tag_name: "nightly"
-          prerelease: true
-          body: ${{ needs.prepare.outputs.changelog }}
-          files: |
-            ${{ steps.artifacts.outputs.file_name }}
+      # # If this is a nightly release, it also updates the release
+      # # tagged `nightly` for compatibility with `ziskup`
+      # - name: Update nightly release
+      #   if: ${{ env.IS_NIGHTLY == 'true' }}
+      #   uses: softprops/action-gh-release@v1
+      #   with:
+      #     name: "Nightly"
+      #     tag_name: "nightly"
+      #     prerelease: true
+      #     body: ${{ needs.prepare.outputs.changelog }}
+      #     files: |
+      #       ${{ steps.artifacts.outputs.file_name }}
 
-  cleanup:
-    name: Release cleanup
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    needs: release
-    if: always()
-    steps:
-      - uses: actions/checkout@v4
+  # cleanup:
+  #   name: Release cleanup
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   needs: release
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      # Moves the `nightly` tag to `HEAD`
-      - name: Move nightly tag
-        if: ${{ env.IS_NIGHTLY }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const moveTag = require('./.github/scripts/move-tag.js')
-            await moveTag({ github, context }, 'nightly')
+  #     # Moves the `nightly` tag to `HEAD`
+  #     - name: Move nightly tag
+  #       if: ${{ env.IS_NIGHTLY }}
+  #       uses: actions/github-script@v7
+  #       with:
+  #         script: |
+  #           const moveTag = require('./.github/scripts/move-tag.js')
+  #           await moveTag({ github, context }, 'nightly')
 
-      - name: Delete old nightlies
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const prunePrereleases = require('./.github/scripts/prune-prereleases.js')
-            await prunePrereleases({github, context})
+  #     - name: Delete old nightlies
+  #       uses: actions/github-script@v7
+  #       with:
+  #         script: |
+  #           const prunePrereleases = require('./.github/scripts/prune-prereleases.js')
+  #           await prunePrereleases({github, context})
