test RUSTFLAGS

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -247,8 +247,8 @@ jobs:
           [[ "$target" == *windows* ]] && exe=".exe"
 
           # RUSTFLAGS with correct path and debugging
-          export RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5"
-          echo "RUSTFLAGS set to: $RUSTFLAGS"
+          # export RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5"
+          # echo "RUSTFLAGS set to: $RUSTFLAGS"
 
           # Debug: Check Rust and Cargo versions
           echo "🔍 Rust and Cargo versions:"
@@ -257,14 +257,14 @@ jobs:
 
           # Build bins with debugging
           echo "🚀 Starting cargo bins build..."
-           cargo build --release -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
-          # RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5" cargo build --release --all-features -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
+          # cargo build --release -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
+          RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5" cargo build --release --all-features -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
           # cargo build --release --target "$target" "${flags[@]}"
 
-          # # Build libzisk_witness.so with debugging
-          # echo "🚀 Starting libzisk_witness.so build..."
-          # RUSTFLAGS="-L${IOMP5_DIR} -liomp5" cargo build --release -p zisk-witness --target "$target" "${flags[@]}"
-          # # cargo build --release --target "$target" "${flags[@]}"
+          # Build libzisk_witness.so with debugging
+          echo "🚀 Starting libzisk_witness.so build..."
+          RUSTFLAGS="-L${IOMP5_DIR} -liomp5" cargo build --release -p zisk-witness --target "$target" "${flags[@]}"
+          # cargo build --release --target "$target" "${flags[@]}"
 
           # Verify built binaries
           bins=(cargo-zisk ziskemu keccakf_fixed_gen riscv2zisk rom-merkle)
@@ -278,13 +278,13 @@ jobs:
             fi
           done
 
-          # libraries=(libzisk_witness.so)
-          # for name in "${libraries[@]}"; do
-          #   bin=./target/$target/release/$name
-          #   echo "🔍 Verifying binary library: $bin"
-          #   file "$bin" || echo "⚠️  file command failed on $bin"
-          #   ldd "$bin" || echo "⚠️  ldd command failed on $bin"
-          # done
+          libraries=(libzisk_witness.so)
+          for name in "${libraries[@]}"; do
+            bin=./target/$target/release/$name
+            echo "🔍 Verifying binary library: $bin"
+            file "$bin" || echo "⚠️  file command failed on $bin"
+            ldd "$bin" || echo "⚠️  ldd command failed on $bin"
+          done
 
           echo "✅ Build process completed."
 
