Add rom-setup

diff --git a/.github/workflows/test_install_bin.yml b/.github/workflows/test_install_bin.yml
--- a/.github/workflows/test_install_bin.yml
+++ b/.github/workflows/test_install_bin.yml
@@ -79,6 +79,16 @@ jobs:
             exit 1
           fi
 
+      - name: Program setup
+        shell: bash
+        run: |
+          cd $HOME/sha_hasher
+          cargo-zisk rom-setup -e target/riscv64ima-polygon-ziskos-elf/release/sha_hasher | tee romsetup_output.log
+          if ! grep -q "ROM setup successfully completed" romsetup_output.log; then
+            echo "❌ Program setup failed"
+            exit 1
+          fi
+  
       - name: Prove program
         shell: bash
         run: |
